# Generated by Django 4.2 on 2025-09-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
