# Generated by Django 4.2 on 2025-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cell_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
