# Generated by Django 4.2 on 2025-09-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_subscriptionplan_subscription_featureusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='USD', max_length=10)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pay_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('actually_paid', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('actually_paid_at_fiat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Payment'), ('confirming', 'Confirming Payment'), ('confirmed', 'Payment Confirmed'), ('sending', 'Processing Payment'), ('partially_paid', 'Partially Paid'), ('finished', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded'), ('expired', 'Invoice Expired')], default='waiting', max_length=20)),
                ('purchase_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('order_description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to='user.profile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to='user.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
