# Generated by Django 4.2 on 2025-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_paymentinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Payment'), ('confirming', 'Confirming Payment'), ('confirmed', 'Payment Confirmed'), ('sending', 'Processing Payment'), ('partially_paid', 'Partially Paid'), ('finished', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded'), ('expired', 'Invoice Expired'), ('cancelled', 'Payment Cancelled')], default='waiting', max_length=20),
        ),
    ]
