version: '3'

services:
  social_api:
    container_name: social_api
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 8030:80
    env_file:
      - .env

  social_celery:
    container_name: social_celery
    build: .
    working_dir: /app/social
    command: ["celery", "-A", "social", "worker", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - social_redis
    env_file:
      - .env

  social_beat:
    container_name: social_beat
    build: .
    working_dir: /app/social
    command: ["celery", "-A", "social", "beat", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - social_redis
    env_file:
      - .env

  social_redis:
    container_name : social_redis
    image: redis:6.2-alpine
    restart: unless-stopped

networks:
  default:
    external:
      name: army