services:
  social_db:
    container_name: social_db
    image: postgres:13.4-alpine
    restart: unless-stopped
    volumes:
      - ./social_db_volume/:/var/lib/postgresql/data
    env_file:
      - .env
    shm_size: 1gb
    networks:
      - social_network
  
  social_api:
    container_name: social_api
    build: .
    restart: unless-stopped
    depends_on:
      - social_db
    volumes:
      - .:/app
      - ./static:/app/social/static
    ports:
      - 127.0.0.1:8030:80
    command: ["python", "/app/social/manage.py", "runserver", "0:80"]
    env_file:
      - .env
    networks:
      - social_network

  social_worker:
    container_name: social_worker
    build: .
    working_dir: /app/social
    command: ["celery", "-A", "social", "worker", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
      - ./static:/app/social/static
    depends_on:
      - social_db
      - social_redis
      - social_firefox
    env_file:
      - .env
    networks:
      - social_network

  social_beat:
    container_name: social_beat
    build: .
    working_dir: /app/social
    command: ["celery", "-A", "social", "beat", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - social_db
      - social_redis
      - social_firefox
    env_file:
      - .env
    networks:
      - social_network

  social_redis:
    container_name : social_redis
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - social_network

  social_firefox:
    container_name : social_firefox
    image: selenium/standalone-firefox:4.7.2-20221219
    ports:
      - 4445:4444
      - 7900:7900
    shm_size: 2g
    restart: unless-stopped
    networks:
      - social_network

networks:
  social_network:
