version: '3'

services:
  social_db:
    container_name: social_db
    image: postgres:13.4-alpine
    restart: unless-stopped
    volumes:
      - social_db:/var/lib/postgresql/data
    env_file:
      - .env
  
  social_api:
    container_name: social_api
    build: .
    restart: unless-stopped
    depends_on:
      - social_db
    volumes:
      - .:/app
      - ./static:/app/social/static
    ports:
      - 8030:80
    command: ["python", "/app/social/manage.py", "runserver", "0:80"]
    env_file:
      - .env

  social_celery:
    container_name: social_celery
    build: .
    working_dir: /app/social
    command: ["celery", "-A", "social", "worker", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
      - ./static:/app/social/static
    depends_on:
      - social_db
      - social_redis
    env_file:
      - .env

  social_beat:
    container_name: social_beat
    build: .
    working_dir: /app/social
    command: ["celery", "-A", "social", "beat", "-l", "info"]
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - social_db
      - social_redis
    env_file:
      - .env

  social_redis:
    container_name : social_redis
    image: redis:6.2-alpine
    restart: unless-stopped

  social_firefox:
    container_name : social_firefox
    image: selenium/standalone-firefox:4.1.4-20220427
    ports:
      - 4445:4444
      - 7900:7900
    shm_size: 2g
    restart: unless-stopped

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5252:80"
  #   restart: unless-stopped

volumes:
  social_db:

networks:
  default:
    name: army