# Generated by Django 4.2 on 2025-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0035_jobsearch_last_crawl_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignoringfilter',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
