# Generated by Django 4.2 on 2025-08-11 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0036_ignoringfilter_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoringFilterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expressionsearch',
            name='ignore_categories',
            field=models.ManyToManyField(blank=True, to='linkedin.ignoringfiltercategory'),
        ),
        migrations.AddField(
            model_name='ignoringfilter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linkedin.ignoringfiltercategory'),
        ),
    ]
