# Generated by Django 4.2 on 2025-08-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0037_ignoringfiltercategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('network_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=40, null=True)),
                ('company_size', models.CharField(blank=True, max_length=100, null=True)),
                ('easy_apply', models.BooleanField(default=False)),
                ('eligible', models.BooleanField(default=True)),
                ('rejected_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='linkedin.jobsearch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
