# Generated by Django 4.2 on 2025-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0038_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='matched_keywords',
            field=models.ManyToManyField(blank=True, to='linkedin.keyword'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='linkedin/keyword_images/'),
        ),
    ]
