# Generated by Django 4.2 on 2025-08-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0039_job_matched_keywords_keyword_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='found_keywords',
            field=models.TextField(blank=True, help_text='Keywords found in job description, comma-separated', null=True),
        ),
    ]
