# Generated by Django 4.2 on 2025-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0040_job_found_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('expression_search', models.ManyToManyField(blank=True, to='linkedin.expressionsearch')),
                ('job_search', models.ManyToManyField(blank=True, to='linkedin.jobsearch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
