# Generated by Django 4.2 on 2025-09-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_is_email_verified_and_more'),
        ('linkedin', '0041_ignoredaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='linkedin.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_jobs', to='user.profile')),
            ],
            options={
                'verbose_name': 'Favorite Job',
                'verbose_name_plural': 'Favorite Jobs',
                'unique_together': {('profile', 'job')},
            },
        ),
    ]
