# Generated by Django 4.2 on 2025-09-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0042_favoritejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('workable', 'Workable')], default='linkedin', help_text='The source website where this job was found', max_length=20),
        ),
    ]
